module.exports = {
    beforeEach: browser => {
        browser.url("https://devmountain-qa.github.io/employee-manager/1.2_Version/index.html")
    },
    after: browser => {
        browser.end()
    },
    'Check the homepage': browser => {
        browser
            .verify.containsText('.titleText', 'Employee Manager')
            .pause(300)
            .verify.containsText('#noEmployee', 'No Employee Selected')
            .pause(300)
    },
    'Modify employee info': browser => {
        browser
            .click('[name="employee1"]')
            .pause(300)
            .clearValue('input[name="nameEntry"]')
            .pause(300)
            .setValue('input[name="nameEntry"]', 'Test Name')
            .pause(300)
            .clearValue('input[name="phoneEntry"]')
            .pause(300)
            .setValue('input[name="phoneEntry"]', '5558675309')
            .pause(300)
            .clearValue('input[name="titleEntry"]')
            .pause(300)
            .setValue('input[name="titleEntry"]', 'HBIC')
            .pause(300)
            .click('[name="save"]')
            .pause(300)
            .verify.containsText('.listContainer', 'Test Name')
            .pause(300)
    },
    'Verify Changed Info Persists': browser => {
        browser
            .click('[name="employee1"]')
            .pause(300)
            .clearValue('input[name="nameEntry"]')
            .pause(300)
            .setValue('input[name="nameEntry"]', 'Test Name')
            .pause(300)
            .clearValue('input[name="phoneEntry"]')
            .pause(300)
            .setValue('input[name="phoneEntry"]', '5558675309')
            .pause(300)
            .clearValue('input[name="titleEntry"]')
            .pause(300)
            .setValue('input[name="titleEntry"]', 'HBIC')
            .pause(300)
            .click('[name="save"]')
            .pause(300)
            .verify.containsText('.listContainer', 'Test Name')
            .pause(3000)
            .click('[name="employee4"]')
            .pause(300)
            .click('[name="employee1"]')
            .pause(300)

    },
    'Verify cancel button does not save changes': browser => {
        browser
            .click('[name="employee8"]')
            .pause(300)
            .clearValue('input[name="nameEntry"]')
            .pause(300)
            .clearValue('input[name="phoneEntry"]')
            .pause(300)
            .clearValue('input[name="titleEntry"]')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .verify.containsText('.listContainer', 'Ruby Estrada')
            .pause(300)
    },
    'Q4H-80 Check that name field wont allow more than 30 characters': browser => {
        browser
            .click('[name="employee1"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee2"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee3"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee4"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee5"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee6"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee7"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee8"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee9"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee10"]')
            .clearValue('input[name="nameEntry"]')
            .setValue('input[name="nameEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The name field must be between 1 and 30 characters long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
    },
    'Q4H-81 Check that error is displayed when more than 10 characters entered for phone': browser => {
        browser
            .click('[name="employee1"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee2"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee3"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee4"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee5"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee6"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee7"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee8"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee9"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
            .click('[name="employee10"]')
            .clearValue('input[name="phoneEntry"]')
            .setValue('input[name="phoneEntry"]', '1234567890123')
            .click('[name="save"]')
            .verify.containsText('.errorMessage', 'The phone number must be 10 digits long.')
            .pause(300)
            .click(".neutralButton")
            .pause(300)
    },
    // 'Q4H-83 Check that title field wont allow more than 30 characters': browser => {
    //     browser
    //         .click('[name="employee1"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee2"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee3"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee4"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee5"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee6"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee7"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee8"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee9"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    //         .click('[name="employee10"]')
    //         .clearValue('input[name="titleEntry"]')
    //         .setValue('input[name="titleEntry"]', 'Lkjlkjlkjlkjlkjl jlkjlkjlkjlkjlkj')
    //         .click('[name="save"]')
    //         .verify.containsText('.errorMessage', 'The title field must be between 1 and 30 characters long.')
    //         .pause(300)
    //         .click(".neutralButton")
    //         .pause(300)
    // },
    'Q4H-84 Add a new employee': browser => {
        browser
            .click('[name="addEmployee"]')
            .waitForElementPresent('[name="employee11"]')
            .click('[name="employee11"]')
            .clearValue('input[name="nameEntry"]')
            .pause(300)
            .setValue('input[name="nameEntry"]', 'newBoss inTown')
            .pause(300)
            .clearValue('input[name="phoneEntry"]')
            .pause(300)
            .setValue('input[name="phoneEntry"]', '1234567890')
            .pause(300)
            .clearValue('input[name="titleEntry"]')
            .pause(300)
            .setValue('input[name="titleEntry"]', 'The Boss of the Boss')
            .pause(300)
            .click('[name="save"]')
            .pause(300)
            .verify.containsText('.listContainer', 'newBoss inTown')
            .pause(300)



    }
}